- README.md
> Added few binary analysis tools and wargames.

- README.md
Hello,
I added some useful reversing tool.
I always use that tools when doing CTF.
Thanks
> Add some useful reversing sites

- README.md
https://github.com/docileninja/ctf_import
> Added ctf_import

- README.md
introducing a new "Self-hosted CTFs" category under "Wargames"
(resolves https://github.com/bkimminich/juice-shop-ctf/issues/1)
> Add juice-shop-ctf

- README.md
[libformatstr](https://github.com/hellman/libformatstr) is a small script to simplify format string exploitation.
> Added libformatstr

- README.md
Added patator and nozzlr bruteforcers.
> Bruteforcers added

- README.md
The previous year competitions have been turned off due to funding constraints.
> PicoCTF no longer available

- README.md
> Added SecGen to Platforms

- README.md
> Add CTFTime Scrapper

- README.md
- [Hone Your Ninja Skills](https://honeyourskills.ninja/) - Hone your circumvention ninja skills in bypassing security controls and most secure codes of 2020s+
> Added honeyourskills.ninja under *Always online CTFs*

- README.md
Kali Linux CTF Blueprints is a book by Cameron Buchanan on creating your own CTF's with Kali Linux. See it here [https://doc.lagout.org/security/Packt.Kali.Linux.CTF.Blueprints.Jul.2014.ISBN.1783985984.pdf]
> add 'Kali Linux CTF Blueprints' to Create

- README.md
> Resolve all dead links

- README.md
Added few more sources to the existing collection of tools.
> Addition to the Library

- README.md
> add SANS HHC

- README.md
> add PentesterLab

- README.md
> Added a new tool (Snow)

- README.md
Added quipquip in crypto tools
> Added site in crypto

- README.md
added information about the CTF game picoCTF by Carnegie Mellon University.
> Added info about picoCTF

- README.md
Added a new Steganography tool used in the picoCTF.
> New Stego tool added

- README.md
Added echoCTF.RED on wargames and on self-hosted CTFs
> Add echoCTF.RED

- README.md
Fixed link on Burp
Added Turbo Intruder - a Burp Suite extension for sending large numbers of HTTP requests
Added Hacker101 CTF platform
> Fixed broken link, add bruteforce tool and one CTF
